### ISSUE TITLE
Decode function?

### ISSUE THREAD

**Issue by redDwarf03** [maxholman/rlp#1]
Hi. I’m looking for a RLP decode function
Could you help me please

**Comment by muhammadsaddamnur** [comment]
Hi @redDwarf03 , how you decode with this package?

**Comment by redDwarf03** [comment]
see https://github.com/redDwarf03/idena_lib_dart/blob/381bbbb56ffda0c71d14e2292f32555fe03ece9b/lib/util/crypto/rlp.dart#L1

**Comment by muhammadsaddamnur** [comment]
@redDwarf03 thanks!!!
but, result on this method only support bytes type?

**Comment by redDwarf03** [comment]
What is your need?
